// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2VGNI8uoCLHrdcuKFbAwHUwNgfy3eqxQ',
    appId: '1:620182523757:web:e7f108c410fe39429dd464',
    messagingSenderId: '620182523757',
    projectId: 'insurance-app-1e135',
    authDomain: 'insurance-app-1e135.firebaseapp.com',
    storageBucket: 'insurance-app-1e135.appspot.com',
    measurementId: 'G-5FLWQ92L51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgJVc1ZeJdI1LdIbR62HJCZyOR3g28HI8',
    appId: '1:620182523757:android:8ded208008c6811b9dd464',
    messagingSenderId: '620182523757',
    projectId: 'insurance-app-1e135',
    storageBucket: 'insurance-app-1e135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7PHIVherHhjHZDDNLt7FBlBMLo-2Ddwo',
    appId: '1:620182523757:ios:b332ec086f3761709dd464',
    messagingSenderId: '620182523757',
    projectId: 'insurance-app-1e135',
    storageBucket: 'insurance-app-1e135.appspot.com',
    iosClientId: '620182523757-nnf7n44ida78ihgdt98kfgv4nuhlmcth.apps.googleusercontent.com',
    iosBundleId: 'com.example.insurerApp',
  );
}
